// Curated list of ~300-400 common generic whole foods to pull from the joined
// USDA SR Legacy + Foundation Foods pool. `keywords` must all appear (case-insensitive
// substring) in the USDA description; `exclude` rules out unwanted variants.

function food(category, name, keywords, exclude) {
  return { category: category, name: name, keywords: keywords, exclude: exclude || [] };
}

module.exports = [
  // ---- Proteins: beef ----
  food('Proteins', 'Ground Beef, 85% Lean, Cooked', ['beef', 'ground', '85', 'crumbles', 'cooked']),
  food('Proteins', 'Ground Beef, 93% Lean, Cooked', ['beef', 'ground', '93', 'crumbles', 'cooked']),
  food('Proteins', 'Ground Beef, 70% Lean, Cooked', ['beef', 'ground', '70', 'crumbles', 'cooked']),
  food('Proteins', 'Beef Top Sirloin, Broiled', ['beef', 'sirloin', 'broiled']),
  food('Proteins', 'Beef Ribeye, Broiled', ['beef', 'rib eye', 'broiled']),
  food('Proteins', 'Beef Tenderloin, Broiled', ['beef', 'tenderloin', 'broiled']),
  food('Proteins', 'Beef Chuck Roast, Braised', ['beef', 'chuck', 'braised']),
  food('Proteins', 'Beef Brisket, Braised', ['beef', 'brisket', 'braised']),
  food('Proteins', 'Beef Flank Steak, Broiled', ['beef', 'flank', 'broiled']),
  food('Proteins', 'Beef Top Round, Broiled', ['beef', 'round', 'top round', 'broiled']),
  food('Proteins', 'Beef Short Ribs, Braised', ['beef', 'short ribs', 'braised']),
  food('Proteins', 'Beef Liver, Pan-Fried', ['beef', 'liver', 'fried']),

  // ---- Proteins: pork ----
  food('Proteins', 'Pork Chop, Broiled', ['pork', 'chop', 'broiled']),
  food('Proteins', 'Pork Tenderloin, Roasted', ['pork', 'tenderloin', 'roasted']),
  food('Proteins', 'Pork Loin, Roasted', ['pork', 'loin', 'roasted'], ['tenderloin']),
  food('Proteins', 'Bacon, Cooked', ['pork', 'bacon', 'cooked'], ['turkey', 'canadian']),
  food('Proteins', 'Ham, Roasted', ['ham', 'roasted'], ['salad', 'spread']),
  food('Proteins', 'Ground Pork, Cooked', ['pork', 'ground', 'cooked']),
  food('Proteins', 'Pork Shoulder, Roasted', ['pork', 'shoulder', 'roasted']),
  food('Proteins', 'Pork Spare Ribs, Braised', ['pork', 'spareribs', 'braised']),

  // ---- Proteins: lamb, bison, venison ----
  food('Proteins', 'Lamb Chop, Broiled', ['lamb', 'chop', 'broiled']),
  food('Proteins', 'Ground Lamb, Cooked', ['lamb', 'ground', 'cooked']),
  food('Proteins', 'Ground Bison, Cooked', ['bison', 'ground', 'cooked']),
  food('Proteins', 'Venison, Raw', ['deer', 'venison', 'raw']),

  // ---- Proteins: poultry ----
  food('Proteins', 'Chicken Breast, Roasted', ['chicken', 'broilers or fryers', 'breast', 'roasted'], ['fried', 'stewed']),
  food('Proteins', 'Chicken Thigh, Roasted', ['chicken', 'thigh', 'roasted'], ['fried']),
  food('Proteins', 'Chicken Drumstick, Roasted', ['chicken', 'drumstick', 'meat and skin', 'roasted'], ['fried', 'battter']),
  food('Proteins', 'Chicken Wing, Roasted', ['chicken', 'wing', 'roasted'], ['fried']),
  food('Proteins', 'Ground Chicken, Cooked', ['chicken', 'ground', 'cooked']),
  food('Proteins', 'Chicken Liver, Cooked', ['chicken', 'liver', 'cooked'], ['pate']),
  food('Proteins', 'Turkey Breast, Roasted', ['turkey', 'breast', 'roasted'], ['deli', 'processed']),
  food('Proteins', 'Ground Turkey, Cooked', ['turkey', 'ground', 'cooked']),
  food('Proteins', 'Turkey Thigh, Roasted', ['turkey', 'thigh', 'roasted']),
  food('Proteins', 'Duck, Roasted', ['duck', 'roasted'], ['liver']),

  // ---- Proteins: fish and seafood ----
  food('Proteins', 'Salmon, Atlantic, Cooked', ['salmon', 'atlantic', 'cooked'], ['smoked']),
  food('Proteins', 'Salmon, Sockeye, Cooked', ['salmon', 'sockeye', 'cooked']),
  food('Proteins', 'Tuna, Canned in Water', ['tuna', 'canned', 'water']),
  food('Proteins', 'Tuna, Yellowfin, Cooked', ['tuna', 'yellowfin', 'cooked']),
  food('Proteins', 'Tilapia, Cooked', ['tilapia', 'cooked']),
  food('Proteins', 'Cod, Cooked', ['cod', 'atlantic', 'cooked'], ['dried', 'salted']),
  food('Proteins', 'Shrimp, Cooked', ['shrimp', 'cooked'], ['breaded', 'imitation']),
  food('Proteins', 'Halibut, Cooked', ['halibut', 'cooked']),
  food('Proteins', 'Sardines, Canned in Oil', ['sardine', 'canned', 'oil']),
  food('Proteins', 'Mackerel, Cooked', ['mackerel', 'atlantic', 'cooked']),
  food('Proteins', 'Trout, Cooked', ['trout', 'cooked']),
  food('Proteins', 'Crab, Cooked', ['crustaceans', 'crab', 'blue', 'cooked'], ['imitation', 'cake']),
  food('Proteins', 'Scallops, Cooked', ['scallop', 'cooked'], ['breaded']),
  food('Proteins', 'Catfish, Cooked', ['catfish', 'cooked'], ['breaded', 'fried']),
  food('Proteins', 'Mahi Mahi, Cooked', ['mahi', 'cooked']),
  food('Proteins', 'Snapper, Cooked', ['snapper', 'cooked']),
  food('Proteins', 'Clams, Cooked', ['clam', 'cooked'], ['canned', 'breaded']),
  food('Proteins', 'Mussels, Cooked', ['mussel', 'cooked']),
  food('Proteins', 'Lobster, Cooked', ['lobster', 'cooked']),
  food('Proteins', 'Oysters, Cooked', ['oyster', 'cooked'], ['breaded']),

  // ---- Proteins: eggs ----
  food('Proteins', 'Egg, Whole, Cooked', ['egg', 'whole', 'cooked', 'hard-boiled']),
  food('Proteins', 'Egg White, Raw', ['egg', 'white', 'raw', 'fresh']),
  food('Proteins', 'Egg Yolk, Raw', ['egg', 'yolk', 'raw', 'fresh']),

  // ---- Proteins: legumes ----
  food('Proteins', 'Black Beans, Cooked', ['beans', 'black', 'cooked'], ['canned']),
  food('Proteins', 'Kidney Beans, Cooked', ['beans', 'kidney', 'cooked'], ['canned']),
  food('Proteins', 'Chickpeas, Cooked', ['chickpea', 'cooked'], ['canned']),
  food('Proteins', 'Lentils, Cooked', ['lentil', 'cooked']),
  food('Proteins', 'Pinto Beans, Cooked', ['beans', 'pinto', 'cooked'], ['canned']),
  food('Proteins', 'Navy Beans, Cooked', ['beans', 'navy', 'cooked'], ['canned']),
  food('Proteins', 'Edamame, Cooked', ['edamame', 'frozen', 'prepared'], ['unprepared']),
  food('Proteins', 'Split Peas, Cooked', ['peas', 'split', 'cooked']),
  food('Proteins', 'Lima Beans, Cooked', ['lima beans', 'cooked'], ['canned']),
  food('Proteins', 'Soybeans, Cooked', ['soybeans', 'mature', 'cooked']),
  food('Proteins', 'Black-Eyed Peas, Cooked', ['cowpeas', 'blackeyes', 'cooked', 'boiled'], ['frozen']),
  food('Proteins', 'Great Northern Beans, Cooked', ['great northern', 'cooked'], ['canned']),
  food('Proteins', 'Fava Beans, Cooked', ['fava beans', 'cooked']),
  food('Proteins', 'Mung Beans, Cooked', ['mung', 'cooked']),

  // ---- Proteins: other ----
  food('Proteins', 'Tofu, Firm', ['tofu', 'firm', 'nigari']),
  food('Proteins', 'Tempeh, Cooked', ['tempeh']),

  // ---- Proteins: more variety ----
  food('Proteins', 'Beef Eye of Round, Roasted', ['beef', 'eye of round', 'roasted']),
  food('Proteins', 'Beef T-Bone Steak, Broiled', ['beef', 't-bone', 'broiled']),
  food('Proteins', 'Beef Skirt Steak, Broiled', ['beef', 'skirt steak', 'broiled']),
  food('Proteins', 'Beef Corned, Cooked', ['beef', 'corned', 'cooked']),
  food('Proteins', 'Turkey Bacon, Cooked', ['bacon', 'turkey', 'microwaved']),
  food('Proteins', 'Cornish Hen, Roasted', ['cornish game hens', 'roasted']),
  food('Proteins', 'Salmon, Pink, Canned', ['salmon', 'pink', 'canned']),
  food('Proteins', 'Salmon, Coho, Cooked', ['salmon', 'coho', 'cooked']),
  food('Proteins', 'Anchovy, Canned in Oil', ['anchov', 'canned', 'oil']),
  food('Proteins', 'Herring, Cooked', ['herring', 'atlantic', 'cooked'], ['pickled']),
  food('Proteins', 'Swordfish, Cooked', ['swordfish', 'cooked']),
  food('Proteins', 'Flounder, Cooked', ['flatfish', 'cooked']),
  food('Proteins', 'Perch, Cooked', ['perch', 'mixed species', 'cooked']),
  food('Proteins', 'Squid, Cooked', ['squid', 'mixed species', 'cooked'], ['fried']),
  food('Proteins', 'Octopus, Cooked', ['octopus', 'cooked']),
  food('Proteins', 'Crayfish, Cooked', ['crayfish', 'cooked']),
  food('Proteins', 'Refried Beans, Canned', ['beans', 'refried', 'canned'], ['fat free']),
  food('Proteins', 'Hummus', ['hummus', 'commercial']),
  food('Proteins', 'Peas, Mature, Cooked', ['peas', 'mature seeds', 'cooked', 'boiled'], ['split']),

  // ---- Grains / Carbs: rice ----
  food('Grains', 'White Rice, Cooked', ['rice', 'white', 'long-grain', 'cooked'], ['fried']),
  food('Grains', 'Brown Rice, Cooked', ['rice', 'brown', 'long-grain', 'cooked']),
  food('Grains', 'Wild Rice, Cooked', ['wild rice', 'cooked']),
  food('Grains', 'Rice, White, Parboiled, Cooked', ['rice', 'white', 'long-grain', 'parboiled', 'enriched', 'cooked']),
  food('Grains', 'Rice, White, Glutinous, Cooked', ['rice', 'white', 'glutinous', 'cooked'], ['uncooked']),

  // ---- Grains / Carbs: bread ----
  food('Grains', 'White Bread', ['bread', 'white', 'commercially'], ['toasted']),
  food('Grains', 'Whole Wheat Bread', ['bread', 'whole-wheat', 'commercially'], ['toasted']),
  food('Grains', 'Rye Bread', ['bread', 'rye']),
  food('Grains', 'Sourdough Bread', ['bread', 'sourdough']),
  food('Grains', 'Bagel, Plain', ['bagels', 'plain', 'enriched'], ['toasted']),
  food('Grains', 'Pita Bread, Whole Wheat', ['pita', 'whole-wheat']),
  food('Grains', 'Corn Tortilla', ['tortilla', 'corn', 'ready-to-bake']),
  food('Grains', 'Flour Tortilla', ['tortilla', 'flour', 'ready-to-bake']),

  // ---- Grains / Carbs: pasta ----
  food('Grains', 'Spaghetti, Cooked', ['spaghetti', 'cooked', 'enriched'], ['whole', 'protein']),
  food('Grains', 'Macaroni, Cooked', ['macaroni', 'cooked', 'enriched'], ['whole']),
  food('Grains', 'Whole Wheat Pasta, Cooked', ['pasta', 'whole', 'cooked'], ['spaghetti']),
  food('Grains', 'Egg Noodles, Cooked', ['noodles', 'egg', 'cooked'], ['unenriched']),

  // ---- Grains / Carbs: oats ----
  food('Grains', 'Oats, Dry', ['oats'], ['cereals ready-to-eat', 'bar', 'babyfood', 'honey bunch']),
  food('Grains', 'Oatmeal, Cooked with Water', ['cereals', 'oats', 'cooked with water'], ['instant']),
  food('Grains', 'Instant Oatmeal, Plain, Cooked', ['cereals', 'oats', 'instant', 'fortified', 'plain', 'prepared with water']),

  // ---- Grains / Carbs: potatoes ----
  food('Grains', 'Potato, Baked with Skin', ['potato', 'baked', 'skin'], ['sweet']),
  food('Grains', 'Potato, Boiled', ['potato', 'boiled'], ['sweet', 'red']),
  food('Grains', 'Sweet Potato, Baked', ['sweet potato', 'baked']),
  food('Grains', 'Red Potato, Baked', ['potatoes', 'red', 'flesh and skin', 'baked']),

  // ---- Grains / Carbs: other ----
  food('Grains', 'Quinoa, Cooked', ['quinoa', 'cooked']),
  food('Grains', 'Barley, Cooked', ['barley', 'pearled', 'cooked']),
  food('Grains', 'Couscous, Cooked', ['couscous', 'cooked']),
  food('Grains', 'Bulgur, Cooked', ['bulgur', 'cooked']),
  food('Grains', 'Cornmeal, Dry', ['cornmeal', 'whole-grain']),
  food('Grains', 'Grits, Cooked', ['corn grits', 'cooked'], ['instant']),
  food('Grains', 'Corn Flakes Cereal', ['corn flakes']),
  food('Grains', 'Shredded Wheat Cereal', ['wheat', 'shredded']),
  food('Grains', 'Millet, Cooked', ['millet', 'cooked']),
  food('Grains', 'Rice Noodles, Cooked', ['rice noodles', 'cooked']),
  food('Grains', 'Cream of Wheat, Cooked', ['wheat', 'farina', 'cooked']),
  food('Grains', 'English Muffin, Plain', ['english muffin', 'plain'], ['toasted']),
  food('Grains', 'Croissant, Butter', ['croissants', 'butter']),
  food('Grains', 'Naan Bread', ['bread', 'naan']),
  food('Grains', 'Rice Cakes, Plain', ['rice cakes', 'brown rice', 'plain']),
  food('Grains', 'Popcorn, Air-Popped', ['popcorn', 'air-popped']),
  food('Grains', 'Whole Wheat Flour', ['wheat flour', 'whole-grain']),
  food('Grains', 'All-Purpose Flour, White', ['wheat flour', 'white', 'all-purpose', 'enriched']),
  food('Grains', 'Buckwheat, Cooked', ['buckwheat', 'groats', 'roasted', 'cooked']),
  food('Grains', 'Amaranth Grain, Cooked', ['amaranth grain', 'cooked']),
  food('Grains', 'Lasagna Noodles, Cooked', ['macaroni', 'cooked'], ['whole', 'vegetable']),
  food('Grains', 'Chow Mein Noodles', ['noodles', 'chinese', 'chow mein']),
  food('Grains', 'Hash Browns', ['potato', 'hash brown']),
  food('Grains', 'Mashed Potatoes, Plain', ['potatoes', 'mashed', 'home-prepared', 'whole milk and butter']),
  food('Grains', 'French Fries, Baked', ['potato', 'french fried', 'oven-heated']),
  food('Grains', 'Yam, Cooked', ['yam', 'cooked'], ['candied']),
  food('Grains', 'Taro, Cooked', ['taro', 'cooked']),
  food('Grains', 'Plantain, Baked', ['plantains', 'yellow', 'baked']),

  // ---- Fruits ----
  food('Fruits', 'Apple, Raw', ['apple', 'raw', 'with skin']),
  food('Fruits', 'Banana, Raw', ['banana', 'raw']),
  food('Fruits', 'Orange, Raw', ['orange', 'raw', 'navel']),
  food('Fruits', 'Grapes, Raw', ['grapes', 'red or green', 'raw']),
  food('Fruits', 'Strawberries, Raw', ['strawberries', 'raw']),
  food('Fruits', 'Blueberries, Raw', ['blueberries', 'raw']),
  food('Fruits', 'Raspberries, Raw', ['raspberries', 'raw']),
  food('Fruits', 'Blackberries, Raw', ['blackberries', 'raw']),
  food('Fruits', 'Watermelon, Raw', ['watermelon', 'raw']),
  food('Fruits', 'Cantaloupe, Raw', ['cantaloupe', 'raw']),
  food('Fruits', 'Honeydew Melon, Raw', ['honeydew', 'raw']),
  food('Fruits', 'Pineapple, Raw', ['pineapple', 'raw']),
  food('Fruits', 'Mango, Raw', ['mango', 'raw']),
  food('Fruits', 'Papaya, Raw', ['papaya', 'raw']),
  food('Fruits', 'Kiwifruit, Raw', ['kiwifruit', 'raw']),
  food('Fruits', 'Peach, Raw', ['peaches', 'raw'], ['canned', 'dried']),
  food('Fruits', 'Pear, Raw', ['pears', 'raw'], ['canned', 'dried']),
  food('Fruits', 'Plum, Raw', ['plums', 'raw']),
  food('Fruits', 'Cherries, Sweet, Raw', ['cherries', 'sweet', 'raw']),
  food('Fruits', 'Apricot, Raw', ['apricots', 'raw'], ['dried']),
  food('Fruits', 'Grapefruit, Raw', ['grapefruit', 'raw', 'pink']),
  food('Fruits', 'Lemon, Raw', ['lemons', 'raw', 'without peel']),
  food('Fruits', 'Lime, Raw', ['limes', 'raw']),
  food('Fruits', 'Pomegranate, Raw', ['pomegranate', 'raw']),
  food('Fruits', 'Fig, Raw', ['figs', 'raw']),
  food('Fruits', 'Dates, Dried', ['dates', 'medjool']),
  food('Fruits', 'Raisins', ['raisins', 'seedless']),
  food('Fruits', 'Avocado, Raw', ['avocado', 'raw', 'california']),
  food('Fruits', 'Coconut Meat, Raw', ['coconut meat', 'raw']),
  food('Fruits', 'Cranberries, Raw', ['cranberries', 'raw']),
  food('Fruits', 'Nectarine, Raw', ['nectarines', 'raw']),
  food('Fruits', 'Tangerine, Raw', ['tangerines', 'raw']),
  food('Fruits', 'Passion Fruit, Raw', ['passion-fruit', 'raw']),
  food('Fruits', 'Guava, Raw', ['guavas', 'common', 'raw']),
  food('Fruits', 'Star Fruit, Raw', ['carambola', 'raw']),
  food('Fruits', 'Persimmon, Raw', ['persimmons', 'japanese', 'raw']),
  food('Fruits', 'Dried Apricots', ['apricots', 'dried']),
  food('Fruits', 'Prunes, Dried', ['prunes', 'dried']),
  food('Fruits', 'Dried Figs', ['figs', 'dried']),
  food('Fruits', 'Dried Cranberries', ['cranberries', 'dried', 'sweetened']),
  food('Fruits', 'Currants, Dried', ['currants', 'zante']),
  food('Fruits', 'Blood Orange, Raw', ['oranges', 'raw', 'all commercial'], ['navel']),
  food('Fruits', 'Cherries, Sour, Raw', ['cherries', 'sour', 'red', 'raw']),
  food('Fruits', 'Elderberries, Raw', ['elderberries', 'raw']),
  food('Fruits', 'Gooseberries, Raw', ['gooseberries', 'raw']),
  food('Fruits', 'Kumquat, Raw', ['kumquats', 'raw']),
  food('Fruits', 'Lychee, Raw', ['litchis', 'raw']),
  food('Fruits', 'Plantain, Raw', ['plantains', 'raw']),
  food('Fruits', 'Rhubarb, Raw', ['rhubarb', 'raw']),
  food('Fruits', 'Breadfruit, Raw', ['breadfruit', 'raw']),
  food('Fruits', 'Jackfruit, Raw', ['jackfruit', 'raw']),
  food('Fruits', 'Mulberries, Raw', ['mulberries', 'raw']),
  food('Fruits', 'Boysenberries, Frozen', ['boysenberries', 'frozen']),
  food('Fruits', 'Applesauce, Unsweetened', ['applesauce', 'unsweetened']),

  // ---- Vegetables ----
  food('Vegetables', 'Broccoli, Raw', ['broccoli', 'raw']),
  food('Vegetables', 'Cauliflower, Raw', ['cauliflower', 'raw']),
  food('Vegetables', 'Carrot, Raw', ['carrots', 'raw']),
  food('Vegetables', 'Celery, Raw', ['celery', 'raw']),
  food('Vegetables', 'Spinach, Raw', ['spinach', 'raw']),
  food('Vegetables', 'Kale, Raw', ['kale', 'raw']),
  food('Vegetables', 'Romaine Lettuce, Raw', ['lettuce', 'romaine', 'raw']),
  food('Vegetables', 'Iceberg Lettuce, Raw', ['lettuce', 'iceberg', 'raw']),
  food('Vegetables', 'Cabbage, Raw', ['cabbage', 'raw'], ['red', 'chinese', 'savoy']),
  food('Vegetables', 'Red Cabbage, Raw', ['cabbage', 'red', 'raw']),
  food('Vegetables', 'Brussels Sprouts, Cooked', ['brussels sprouts', 'cooked'], ['frozen']),
  food('Vegetables', 'Asparagus, Cooked', ['asparagus', 'cooked'], ['frozen', 'canned']),
  food('Vegetables', 'Green Beans, Cooked', ['beans', 'snap', 'green', 'cooked'], ['canned', 'frozen']),
  food('Vegetables', 'Peas, Green, Cooked', ['peas', 'green', 'cooked'], ['canned', 'frozen']),
  food('Vegetables', 'Corn, Sweet, Cooked', ['corn', 'sweet', 'yellow', 'cooked'], ['canned', 'frozen']),
  food('Vegetables', 'Zucchini, Raw', ['squash', 'zucchini', 'raw']),
  food('Vegetables', 'Cucumber, Raw', ['cucumber', 'raw', 'with peel']),
  food('Vegetables', 'Tomato, Raw', ['tomatoes', 'red', 'ripe', 'raw']),
  food('Vegetables', 'Bell Pepper, Red, Raw', ['peppers', 'sweet', 'red', 'raw']),
  food('Vegetables', 'Bell Pepper, Green, Raw', ['peppers', 'sweet', 'green', 'raw']),
  food('Vegetables', 'Onion, Yellow, Raw', ['onions', 'raw'], ['spring', 'welsh']),
  food('Vegetables', 'Garlic, Raw', ['garlic', 'raw']),
  food('Vegetables', 'Mushroom, White, Raw', ['mushrooms', 'white', 'raw']),
  food('Vegetables', 'Eggplant, Cooked', ['eggplant', 'cooked'], ['boiled']),
  food('Vegetables', 'Butternut Squash, Cooked', ['squash', 'butternut', 'cooked']),
  food('Vegetables', 'Acorn Squash, Cooked', ['squash', 'acorn', 'cooked']),
  food('Vegetables', 'Pumpkin, Cooked', ['pumpkin', 'cooked'], ['canned']),
  food('Vegetables', 'Beet, Cooked', ['beets', 'cooked'], ['canned', 'pickled']),
  food('Vegetables', 'Radish, Raw', ['radishes', 'raw']),
  food('Vegetables', 'Artichoke, Cooked', ['artichoke', 'globe', 'cooked']),
  food('Vegetables', 'Okra, Cooked', ['okra', 'cooked'], ['fried', 'frozen']),
  food('Vegetables', 'Leek, Cooked', ['leeks', 'cooked']),
  food('Vegetables', 'Turnip, Cooked', ['turnips', 'cooked']),
  food('Vegetables', 'Parsnip, Cooked', ['parsnips', 'cooked']),
  food('Vegetables', 'Collard Greens, Cooked', ['collards', 'cooked'], ['frozen', 'canned']),
  food('Vegetables', 'Swiss Chard, Cooked', ['chard', 'swiss', 'cooked']),
  food('Vegetables', 'Bok Choy, Cooked', ['cabbage', 'chinese', 'pak-choi', 'cooked']),
  food('Vegetables', 'Snow Peas, Cooked', ['peas', 'edible', 'pod', 'cooked']),
  food('Vegetables', 'Scallion, Raw', ['onions', 'spring', 'raw']),
  food('Vegetables', 'Shallot, Raw', ['shallots', 'raw']),
  food('Vegetables', 'Jicama, Raw', ['yambean', 'raw']),
  food('Vegetables', 'Rutabaga, Cooked', ['rutabagas', 'cooked']),
  food('Vegetables', 'Green Onion, Raw', ['onions', 'welsh', 'raw']),
  food('Vegetables', 'Portobello Mushroom, Grilled', ['mushrooms', 'portabella', 'grilled']),
  food('Vegetables', 'Snap Peas, Raw', ['peas', 'edible', 'pod', 'raw']),
  food('Vegetables', 'Kohlrabi, Cooked', ['kohlrabi', 'cooked']),
  food('Vegetables', 'Chayote, Cooked', ['chayote', 'cooked']),
  food('Vegetables', 'Fennel Bulb, Raw', ['fennel', 'bulb', 'raw']),
  food('Vegetables', 'Endive, Raw', ['endive', 'raw']),
  food('Vegetables', 'Arugula, Raw', ['arugula', 'raw']),
  food('Vegetables', 'Watercress, Raw', ['watercress', 'raw']),
  food('Vegetables', 'Mustard Greens, Cooked', ['mustard greens', 'cooked'], ['frozen', 'canned']),
  food('Vegetables', 'Turnip Greens, Cooked', ['turnip greens', 'cooked'], ['frozen', 'canned']),
  food('Vegetables', 'Beet Greens, Cooked', ['beet greens', 'cooked']),
  food('Vegetables', 'Dandelion Greens, Cooked', ['dandelion greens', 'cooked']),
  food('Vegetables', 'Spaghetti Squash, Cooked', ['squash', 'spaghetti', 'cooked']),
  food('Vegetables', 'Summer Squash, Yellow, Cooked', ['squash', 'summer', 'crookneck', 'cooked'], ['frozen', 'canned']),
  food('Vegetables', 'Portobello Mushroom, Raw', ['mushrooms', 'portabella', 'raw']),
  food('Vegetables', 'Shiitake Mushroom, Cooked', ['mushrooms', 'shiitake', 'cooked'], ['dried']),
  food('Vegetables', 'Cremini Mushroom, Raw', ['mushrooms', 'brown', 'italian', 'crimini', 'raw']),
  food('Vegetables', 'Red Onion, Raw', ['onions', 'red', 'raw']),
  food('Vegetables', 'Sweet Onion, Raw', ['onions', 'sweet', 'raw']),
  food('Vegetables', 'Ginger Root, Raw', ['ginger root', 'raw']),
  food('Vegetables', 'Jalapeno Pepper, Raw', ['peppers', 'jalapeno', 'raw']),
  food('Vegetables', 'Pasilla Pepper, Dried', ['peppers', 'pasilla', 'dried']),
  food('Vegetables', 'Yellow Bell Pepper, Raw', ['peppers', 'sweet', 'yellow', 'raw']),
  food('Vegetables', 'Tomatillo, Raw', ['tomatillos', 'raw']),
  food('Vegetables', 'Sun-Dried Tomato', ['tomatoes', 'sun-dried'], ['oil']),
  food('Vegetables', 'Water Chestnuts, Canned', ['chestnuts', 'water', 'canned']),
  food('Vegetables', 'Bamboo Shoots, Canned', ['bamboo shoots', 'canned']),
  food('Vegetables', 'Alfalfa Sprouts, Raw', ['alfalfa seeds', 'sprouted', 'raw']),

  // ---- Dairy ----
  food('Dairy', 'Milk, Whole', ['milk', 'whole', '3.25'], ['dry', 'condensed', 'evaporated', 'chocolate']),
  food('Dairy', 'Milk, 2% Reduced Fat', ['milk', 'reduced fat', '2'], ['chocolate']),
  food('Dairy', 'Milk, 1% Low Fat', ['milk', 'lowfat', '1'], ['chocolate']),
  food('Dairy', 'Milk, Skim', ['milk', 'nonfat', 'fluid'], ['dry', 'chocolate']),
  food('Dairy', 'Yogurt, Plain, Whole Milk', ['yogurt', 'plain', 'whole milk']),
  food('Dairy', 'Yogurt, Plain, Low Fat', ['yogurt', 'plain', 'low fat']),
  food('Dairy', 'Greek Yogurt, Plain', ['yogurt', 'greek', 'plain']),
  food('Dairy', 'Cheddar Cheese', ['cheese', 'cheddar']),
  food('Dairy', 'Mozzarella Cheese', ['cheese', 'mozzarella', 'whole milk'], ['low moisture']),
  food('Dairy', 'Swiss Cheese', ['cheese', 'swiss']),
  food('Dairy', 'Parmesan Cheese', ['cheese', 'parmesan']),
  food('Dairy', 'Cottage Cheese', ['cheese', 'cottage', 'creamed'], ['low fat']),
  food('Dairy', 'Cream Cheese', ['cheese', 'cream'], ['fat free', 'light']),
  food('Dairy', 'Feta Cheese', ['cheese', 'feta']),
  food('Dairy', 'Goat Cheese', ['cheese', 'goat']),
  food('Dairy', 'Provolone Cheese', ['cheese', 'provolone']),
  food('Dairy', 'Brie Cheese', ['cheese', 'brie']),
  food('Dairy', 'Blue Cheese', ['cheese', 'blue']),
  food('Dairy', 'Ricotta Cheese', ['cheese', 'ricotta', 'whole milk']),
  food('Dairy', 'Butter, Salted', ['butter', 'salted'], ['whipped']),
  food('Dairy', 'Sour Cream', ['sour cream'], ['fat free', 'light']),
  food('Dairy', 'Half and Half', ['cream', 'fluid', 'half and half'], ['lowfat', 'fat free']),
  food('Dairy', 'Heavy Cream', ['cream', 'heavy']),
  food('Dairy', 'Buttermilk', ['buttermilk', 'fluid']),
  food('Dairy', 'Monterey Jack Cheese', ['cheese', 'monterey']),
  food('Dairy', 'Colby Cheese', ['cheese', 'colby']),
  food('Dairy', 'Evaporated Milk', ['milk', 'evaporated'], ['condensed']),
  food('Dairy', 'Whipped Cream', ['cream', 'whipped', 'pressurized']),
  food('Dairy', 'Yogurt, Vanilla, Low Fat', ['yogurt', 'vanilla', 'low fat']),
  food('Dairy', 'Kefir, Plain', ['kefir']),
  food('Dairy', 'Gouda Cheese', ['cheese', 'gouda']),
  food('Dairy', 'Muenster Cheese', ['cheese', 'muenster']),
  food('Dairy', 'Gruyere Cheese', ['cheese', 'gruyere']),
  food('Dairy', 'Queso Fresco', ['cheese', 'fresh', 'queso fresco']),
  food('Dairy', 'Cream, Light', ['cream', 'light', 'coffee cream']),
  food('Dairy', 'Ice Cream, Vanilla', ['ice creams', 'vanilla'], ['light', 'soft serve']),
  food('Dairy', 'Frozen Yogurt, Vanilla', ['yogurt', 'frozen', 'vanilla'], ['soft serve']),
  food('Dairy', 'Goat Milk', ['milk', 'goat', 'fluid']),
  food('Dairy', 'Sheep Milk', ['milk', 'sheep', 'fluid']),

  // ---- Fats / Oils ----
  food('Fats', 'Olive Oil', ['oil', 'olive', 'salad or cooking']),
  food('Fats', 'Vegetable Oil', ['oil', 'vegetable', 'soybean']),
  food('Fats', 'Canola Oil', ['oil', 'canola']),
  food('Fats', 'Coconut Oil', ['oil', 'coconut']),
  food('Fats', 'Avocado Oil', ['oil', 'avocado']),
  food('Fats', 'Sesame Oil', ['oil', 'sesame', 'salad or cooking']),
  food('Fats', 'Peanut Oil', ['oil', 'peanut']),
  food('Fats', 'Corn Oil', ['oil', 'corn', 'industrial and retail']),
  food('Fats', 'Sunflower Oil', ['oil', 'sunflower', 'linoleic']),
  food('Fats', 'Margarine', ['margarine', 'regular', 'stick'], ['spread']),
  food('Fats', 'Lard', ['lard']),
  food('Fats', 'Mayonnaise', ['mayonnaise', 'regular'], ['light', 'imitation']),
  food('Fats', 'Ghee', ['butter oil', 'anhydrous']),
  food('Fats', 'Flaxseed Oil', ['oil', 'flaxseed']),
  food('Fats', 'Walnut Oil', ['oil', 'walnut']),
  food('Fats', 'Grapeseed Oil', ['oil', 'grapeseed']),
  food('Fats', 'Safflower Oil', ['oil', 'safflower', 'high oleic']),
  food('Fats', 'Shortening, Vegetable', ['shortening', 'household', 'soybean']),
  food('Fats', 'Beef Tallow', ['fat', 'beef', 'tallow']),

  // ---- Nuts / Seeds ----
  food('Nuts', 'Almonds, Raw', ['nuts', 'almonds'], ['roasted', 'honey', 'blanched', 'oil']),
  food('Nuts', 'Walnuts, English', ['nuts', 'walnuts', 'english']),
  food('Nuts', 'Cashews, Raw', ['cashew', 'raw']),
  food('Nuts', 'Pecans', ['nuts', 'pecans'], ['roasted', 'oil']),
  food('Nuts', 'Pistachios, Raw', ['pistachio', 'raw']),
  food('Nuts', 'Peanuts, Raw', ['peanuts', 'all types', 'raw']),
  food('Nuts', 'Peanut Butter, Smooth', ['peanut butter', 'smooth'], ['reduced']),
  food('Nuts', 'Almond Butter', ['almond butter'], ['reduced']),
  food('Nuts', 'Brazil Nuts, Dried', ['brazilnuts', 'dried']),
  food('Nuts', 'Macadamia Nuts, Raw', ['macadamia', 'raw']),
  food('Nuts', 'Hazelnuts', ['nuts', 'hazelnuts or filberts'], ['roasted', 'blanched']),
  food('Nuts', 'Pine Nuts, Dried', ['pine nuts', 'dried'], ['pinyon']),
  food('Nuts', 'Chia Seeds, Dried', ['chia seeds', 'dried']),
  food('Nuts', 'Flaxseeds, Whole', ['seeds', 'flaxseed']),
  food('Nuts', 'Pumpkin Seeds, Roasted', ['pumpkin', 'seeds', 'roasted'], ['salted']),
  food('Nuts', 'Sunflower Seeds, Dry Roasted', ['sunflower seed kernels', 'dry roasted', 'salt added']),
  food('Nuts', 'Sesame Seeds, Whole', ['sesame seeds', 'whole', 'dried']),
  food('Nuts', 'Tahini', ['tahini']),
  food('Nuts', 'Walnuts, Black, Dried', ['nuts', 'walnuts', 'black', 'dried']),
  food('Nuts', 'Cashew Butter', ['cashew butter']),
  food('Nuts', 'Sunflower Seed Butter', ['sunflower seed butter']),
  food('Nuts', 'Soy Nuts, Roasted', ['soybeans', 'roasted']),
  food('Nuts', 'Pistachio, Dry Roasted', ['pistachio', 'dry roasted'], ['salted'])
];
